import { StyleSheet } from "react-native";

import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import fonts, { fontFamily } from "../fonts/fonts";
import Colors from "./color";
//Styles used in this screen are defined here
const MeasurementPageStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: "white",
  },
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  heading: {
    fontSize: 18,
  },
  dropdownSelector: {
    height: hp("5%"),
    width: wp("90%"),
    borderColor: "#B4CFDA",
    alignItems: "center",
    flexDirection: "row",
    alignSelf: "center",
    justifyContent: "space-between",
  },
  arrowStyle: {
    marginRight: wp("5%"),
  },
  arrowStyleTopTitles: {
    marginLeft: wp("14%"),
    alignSelf: "flex-end",
    marginTop: hp("1.5%"),
  },
  FecalScore1: {
    height: 44,
    width: 353,
    borderColor: "#B4CFDA",
    alignItems: "center",
    flexDirection: "row",
    paddingLeft: 15,
    paddingRight: 15,
    alignSelf: "center",
    justifyContent: "space-between",
    borderRadius: 0.5,
  },
  countContainer: {
    alignItems: "center",
    padding: 10,
  },
  button: {
    alignItems: "center",
    marginLeft: 10,
    marginRight: 10,
    backgroundColor: "#136DA533",
    marginTop: 5,
    height: 35,
    width: 323,
  },
  countText: {
    color: "#ED0505",
    fontSize: 24,
  },

  locationNameBgStyle: {
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    borderColor: "#242E4226",
    borderWidth: 1,
  },
  topTileStyle: {
    backgroundColor: "#FFFFFF",
    borderColor: "#242E4226",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 15,
    height: hp("4.5%"),
    width: wp("45%"),
  },
  topTilesContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: hp("1%"),
    padding: 5,
    marginLeft: wp("3%"),
    marginRight: wp("3%"),
    marginTop: hp("1%"),
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  locationName: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 20,
    margin: 10,
  },
  ListItemStyle: {
    marginLeft: wp("3%"),
    marginRight: wp("3%"),
    marginBottom: hp("1%"),
    flex: 1,
  },

  DropdownArea: {
    width: wp("85%"),
    borderColor: "#B4CFDA",
    elevation: 5,
  },
  CommentsInput: {
    height: hp("8%"),
    width: wp("85%"),
    borderRadius: 5,
    borderColor: "#FFFFFF",
    alignSelf: "center",
    marginTop: hp("2%"),
    backgroundColor: "#FFFFFF",
    paddingLeft: 15,
    paddingRight: 20,
    fontFamily: fontFamily.regular,
  },
  centerView: {
    justifyContent: "space-around",
    flexDirection: "row",
    marginLeft: wp("2%"),
    marginRight: wp("2%"),
  },
  buttonDeselected: {
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    width: wp("85%"),
    height: hp("4%"),
    borderRadius: 5,
    marginTop: hp("1%"),
    justifyContent: "space-evenly",
  },

  buttonSelected: {
    backgroundColor: "#136DA3",
    width: wp("35%"),
    height: hp("3%"),
    borderRadius: 5,
    marginTop: hp("1%"),
    marginRight: wp("2%"),
    marginLeft: wp("5%"),
  },
  textWhite: {
    textAlign: "center",
    color: "white",
    fontSize: fonts.fontSmall,
    marginLeft: wp("2%"),
    marginRight: wp("2%"),
    marginTop: hp("0.5%"),
    fontFamily: "Lexend-SemiBold",
  },
  text: {
    textAlign: "center",
    color: "rgba(255, 255, 255, 1)",
    fontSize: fonts.fontSmall,
    marginLeft: wp("2%"),
    marginRight: wp("2%"),
    // marginTop: hp("0.5%"),
    fontFamily: fontFamily.regular,
  },
  // dvctext: {
  //   textAlign: "center",
  //   color: "rgba(255, 255, 255, 1)",
  //   fontSize: fonts.fontSmall,
  //   marginLeft: wp("2%"),
  //   marginRight: wp("2%"),
  //  // marginTop: hp("0.5%"),
  //   fontFamily: fontFamily.semibold,
  // },
  dateContainer: {
    //alignItems: "center",
    justifyContent: "center",
    //padding: 2,
    borderRadius: 5,
    backgroundColor: "#136DA5",
    height: hp("2.5%"),
    marginRight: wp("2%"),
    //right: 70,
    // position: "absolute",
  },
  dateContainerRed: {
    //alignItems: "center",
    justifyContent: "center",
    //padding: 2,
    borderRadius: 5,
    backgroundColor: "#EE4E4E",
    height: hp("2.5%"),
    marginRight: wp("2%"),
    //right: 70,
    // position: "absolute",
  },
  checkBoxContainer: {
    //alignItems: "flex-end",
    justifyContent: "center",
    // padding: 2,
    borderRadius: 5,
    height: hp("2.5%"),
    marginRight: wp("2%"),
    //right: 40,
    //position: "absolute",
  },
  textWhiteSmall: {
    textAlign: "center",
    color: "white",
    fontSize: fonts.fontXXXTiny,
    marginLeft: wp("2%"),
    marginRight: wp("2%"),
    fontFamily: fontFamily.semibold,
  },
  textSmall: {
    textAlign: "left",
    color: Colors.BLACK,
    fontSize: fonts.fontSmall,
    // marginLeft: wp("2%"),
    marginRight: wp("2%"),
    fontFamily: fontFamily.semibold,
  },
  textTitle: {
    textAlign: "left",
    color: Colors.BLACK,
    fontSize: fonts.fontTiny,
    // marginLeft: wp("2%"),
    marginRight: wp("2%"),
    fontFamily: fontFamily.light,
  },
  textSmallLight: {
    textAlign: "left",
    color: Colors.BLACK,
    fontSize: fonts.fontMedium,
    // marginLeft: wp("2%"),
    marginRight: wp("2%"),
    fontFamily: fontFamily.regular,
  },
  dvctext: {
    textAlign: "center",
    color: "rgba(255, 255, 255, 1)",
    fontSize: fonts.fontXSmall,
    marginLeft: wp("2%"),
    marginRight: wp("2%"),
    fontFamily: fontFamily.semibold,
  },
  animalImage: {
    width: 50,
    height: 50,
    marginRight: 10,
     borderRadius: 25,
  },
  animalIcon: {
    width: 25,
    height: 25,
    marginRight: wp("2%"),
    borderRadius: 10.5,
  },
  listBoxStyle: {
    borderRadius: 10,
    borderColor: "#398FC5",
    borderWidth: 1,
  },
  operationTextStyle: {
    fontSize: 16,
    margin: 8,
  },
  contentContainer: {
    //marginTop: hp("1%"),
    alignItems: "center",
    borderColor: Colors.LIGHT_GRAY,
    borderTopRightRadius: 15,
    borderTopLeftRadius: 15,
    borderBottomColor: "white",
    shadowColor: Colors.LIGHT_GRAY,
    borderWidth: 1,
    justifyContent: "center",
    marginBottom: hp("2%"),
  },
  calenderStyle: {
    backgroundColor: "#F1F9E8",
    marginTop: hp("2%"),
    borderBottomColor: Colors.BORDER_COLOR,
    borderWidth: 0.5,
  },
  buttonOut: {
    backgroundColor: "#eaeae8",
    height: hp("3%"),
    width: wp("4%"),
  },
  buttonPressed: {
    backgroundColor: "white",
    height: hp("2.5%"),
    width: wp("3.5%"),
  },
  textBlackTitle: {
    fontSize: fonts.fontXSmall,
    fontFamily: fontFamily.semibold,
    color: Colors.BLACK,
    marginBottom: hp("1%"),
    marginTop: hp("1%"),
  },
});
export default MeasurementPageStyles;
